version: '2'
services:
  webspoon:
    image: hiromuhota/webspoon:latest-full
    ports:
      - "80:8080"
    volumes:
      - /root/.kettle
      - /root/.pentaho
    environment:
      - "JAVA_OPTS=-Xms1024m -Xmx2048m"
volumes:
  kettle:
  pentaho:
