apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.9.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: webspoon
  name: webspoon
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: webspoon
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xms1024m -Xmx2048m
        - name: KETTLE_HOME
          value: /root/.pentaho/.kettle
        image: 016526250478.dkr.ecr.us-west-1.amazonaws.com/pentaho-webspoon:latest-full
        name: webspoon
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /root/.pentaho
          name: webspoon-claim0
        imagePullPolicy: Never
      restartPolicy: Always
      volumes:
      - name: webspoon-claim0
        persistentVolumeClaim:
          claimName: webspoon-claim0
status: {}
